spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fund?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useAffectedRows=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      max-lifetime: 30000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

server:
  port: 9200
  servlet:
    context-path: /fund

url:
  fund: https://fundgz.1234567.com.cn/js/{code}.js?rt=