spring:
  application:
    name: fund
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fund?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useAffectedRows=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      max-lifetime: 30000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

server:
  port: 9200
  servlet:
    context-path: /fund

url:
  fund: https://fundgz.1234567.com.cn/js/{code}.js?rt=

job:
  addresses: http://127.0.0.1:8000/xxl-job-admin
  accessToken: root
  executor:
    appname: fund
    address: http://127.0.0.1:1000
    ip:
    port: 9201
    logpath: /nagisa/logs/fund/job
    logretentiondays: 10

zlp:
  system:
    name: fund
    platform-url: http://127.0.0.1:7000

msg:
  enabled: true
  topic: fund
  msg-type: 1